pipeline {
    agent any {
              stage('Build') {
                  steps{
                      echo 'Hello Build'
                       }
              }
              stage('QA') {
                  steps {    
                  input('Do you want to proceed?')
                 }
              }
   }
}
