pipeline {
    agent any 
    stages {    
         stage('Build') {
                  steps{
                      echo 'Hello Build'
                  }
              }
         stage('QA') {
                  steps {    
                  input('Do you want to proceed?')
                 }
              }
    }
}
